from bin_calc.type_defs import BinaryNumber, DecimalNumber, HexNumber

def bin_to_dec(binary: BinaryNumber) -> int: ...
def dec_to_bin(decimal: DecimalNumber, width: int = 8) -> BinaryNumber: ...

def dec_to_hex(decimal: DecimalNumber) -> HexNumber: ...