def is_binary_string(value: str) -> bool: ...
def is_eight_bit_binary(value: str) -> bool: ...
def require_binary_string(value: str, name: str = "value") -> None: ...
def require_eight_bit_binary(value: str, name: str = "value") -> None: ...